// Lojas físicas da Meteora (dados estáticos — edite livremente).
export const stores = [
  {
    id: 1,
    name: "Meteora Paulista",
    address: "Av. Paulista, 1000 - Bela Vista",
    city: "São Paulo",
    state: "SP",
    phone: "(11) 3000-1000",
    hours: "Seg a Sáb: 10h–22h · Dom: 14h–20h",
  },
  {
    id: 2,
    name: "Meteora Faria Lima",
    address: "Av. Brigadeiro Faria Lima, 2232 - Jardim Paulistano",
    city: "São Paulo",
    state: "SP",
    phone: "(11) 3000-2000",
    hours: "Seg a Sáb: 10h–22h · Dom: 14h–20h",
  },
  {
    id: 3,
    name: "Meteora Barra",
    address: "Av. das Américas, 4666 - Barra da Tijuca",
    city: "Rio de Janeiro",
    state: "RJ",
    phone: "(21) 3000-3000",
    hours: "Seg a Sáb: 10h–22h · Dom: 15h–21h",
  },
  {
    id: 4,
    name: "Meteora Savassi",
    address: "Rua Pernambuco, 1322 - Savassi",
    city: "Belo Horizonte",
    state: "MG",
    phone: "(31) 3000-4000",
    hours: "Seg a Sex: 10h–21h · Sáb: 10h–18h",
  },
  {
    id: 5,
    name: "Meteora Moinhos",
    address: "Rua Padre Chagas, 300 - Moinhos de Vento",
    city: "Porto Alegre",
    state: "RS",
    phone: "(51) 3000-5000",
    hours: "Seg a Sex: 10h–20h · Sáb: 10h–18h",
  },
  {
    id: 6,
    name: "Meteora Boa Viagem",
    address: "Av. Conselheiro Aguiar, 2500 - Boa Viagem",
    city: "Recife",
    state: "PE",
    phone: "(81) 3000-6000",
    hours: "Seg a Sáb: 10h–22h · Dom: 14h–20h",
  },
];
